### ISSUE TITLE
"Cannot read property 'name' of undefined" while installing with ember-cli 0.2.5

### ISSUE THREAD

**Issue by tommyblue** [simplabs/ember-cli-simple-auth-torii#16]
This is the error
```
$ ember install ember-cli-simple-auth-torii
version: 0.2.5
Installed packages for tooling via npm.
Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at /Users/tommyblue/Devel/Phoops/mint-frontend/node_modules/ember-cli/lib/models/project.js:475:53
    at baseFindIndex (/Users/tommyblue/Devel/Phoops/mint-frontend/node_modules/ember-cli/node_modules/lodash/internal/baseFindIndex.js:16:9)
    at /Users/tommyblue/Devel/Phoops/mint-frontend/node_modules/ember-cli/node_modules/lodash/internal/createFind.js:18:19
    at Project.findAddonByName (/Users/tommyblue/Devel/Phoops/mint-frontend/node_modules/ember-cli/lib/models/project.js:474:20)
    at Class.module.exports.Task.extend.findDefaultBlueprintName (/Users/tommyblue/Devel/Phoops/mint-frontend/node_modules/ember-cli/lib/tasks/addon-install.js:63:30)
    at Class.module.exports.Task.extend.installBlueprint (/Users/tommyblue/Devel/Phoops/mint-frontend/node_modules/ember-cli/lib/tasks/addon-install.js:52:30)
    at Class.<anonymous> (/Users/tommyblue/Devel/Phoops/mint-frontend/node_modules/ember-cli/lib/tasks/addon-install.js:42:19)
    at lib$rsvp$$internal$$tryCatch (/Users/tommyblue/Devel/Phoops/mint-frontend/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/tommyblue/Devel/Phoops/mint-frontend/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/Users/tommyblue/Devel/Phoops/mint-frontend/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:472:11)
```

**Comment by vmalloc** [comment]
+1. Happened to me too.

**Comment by Dragsbaek** [comment]
+1

**Comment by jackmatt2** [comment]
Getting this also.
