### ISSUE TITLE
Cannot call method 'writeLine' of undefined

### ISSUE THREAD

**Issue by Mak-Di** [simplabs/ember-cli-simple-auth-torii#9]
```
npm install --save-dev ember-cli-simple-auth // OK
ember generate ember-cli-simple-auth // OK
npm install --save-dev ember-cli-simple-auth-torii // OK

ember generate ember-cli-simple-auth-torii  // Fail
Cannot call method 'writeLine' of undefined
TypeError: Cannot call method 'writeLine' of undefined
    at AddonDiscovery.<anonymous> (/home/ubuntu/fc/node_modules/ember-cli/lib/models/addon-discovery.js:109:22)
    at Array.map (native)
    at AddonDiscovery.discoverFromDependencies (/home/ubuntu/fc/node_modules/ember-cli/lib/models/addon-discovery.js:94:68)
    at AddonDiscovery.discoverChildAddons (/home/ubuntu/fc/node_modules/ember-cli/lib/models/addon-discovery.js:61:31)
    at Class.Addon.discoverAddons (/home/ubuntu/fc/node_modules/ember-cli/lib/models/addon.js:172:40)
    at Class.Addon.initializeAddons (/home/ubuntu/fc/node_modules/ember-cli/lib/models/addon.js:188:8)
    at setupRegistryForEachAddon (/home/ubuntu/fc/node_modules/ember-cli/lib/preprocessors.js:18:10)
    at Object.module.exports.setupRegistry (/home/ubuntu/fc/node_modules/ember-cli/lib/preprocessors.js:46:3)
    at Class.Addon (/home/ubuntu/fc/node_modules/ember-cli/lib/models/addon.js:83:5)
    at new Class (/home/ubuntu/fc/node_modules/ember-cli/node_modules/core-object/core-object.js:16:17)
```

Ember-cli: 0.2.0

**Comment by marcoow** [comment]
install `ember-cli-simple-auth-torii` from the github repo for now - the fix will go out with the next release.
